name: Release

on:
  release:
    types:
      - published

jobs:
  release-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t mahdikhashan/99mails
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
      - run: docker push mahdikhashan/99mails
